const os = require('node:os')

console.log('Información del Sistema Operativo')
console.log('--------------------------------')
console.log(`Sistema Operativo: ${os.platform()}`)
console.log(`Versión del Sistema Operativo: ${os.release()}`)
console.log(`Arquitectura: ${os.arch()}`)
console.log(`Memoria disponible: ${os.freemem() / 1024 / 1024 / 1024} GB`)
console.log(`Memoria total: ${os.totalmem() / 1024 / 1024 / 1024} GB`)
console.log('uptime: ' + os.uptime() + ' segundos')